export PLATFORM = asap7
export DESIGN_NAME = PEPlanaria
export DESIGN_NICKNAME = PEPlanaria
export VERILOG_FILES = $(sort $(wildcard ./designs/src/$(DESIGN_NICKNAME)/*.v))
export SDC_FILE = ./designs/$(PLATFORM)/$(DESIGN_NICKNAME)/constraint.sdc
export IO_CONSTRAINTS = ./designs/$(PLATFORM)/$(DESIGN_NICKNAME)/io.tcl
export DIE_AREA = 0 0 13.7 13.7
export CORE_AREA = 0 0 13.7 13.7
export PLACE_DENSITY = 0.9
