export PLATFORM = asap7
export DESIGN_NAME = PEWS
export DESIGN_NICKNAME = PEWS
export VERILOG_FILES = $(sort $(wildcard ./designs/src/$(DESIGN_NICKNAME)/*.v))
export SDC_FILE = ./designs/$(PLATFORM)/$(DESIGN_NICKNAME)/constraint.sdc
export IO_CONSTRAINTS = ./designs/$(PLATFORM)/$(DESIGN_NICKNAME)/io.tcl
export DIE_AREA = 0 0 15 15
export CORE_AREA = 1 1 14 14
export PLACE_DENSITY = 0.9
