export PLATFORM = asap7
export DESIGN_NAME = PESARA2
export DESIGN_NICKNAME = PESARA2
export VERILOG_FILES = $(sort $(wildcard ./designs/src/$(DESIGN_NICKNAME)/*.v))
export SDC_FILE = ./designs/$(PLATFORM)/$(DESIGN_NICKNAME)/constraint.sdc
export IO_CONSTRAINTS = ./designs/$(PLATFORM)/$(DESIGN_NICKNAME)/io.tcl
export DIE_AREA = 0 0 61 61
export CORE_AREA = 1 1 60 60
export PLACE_DENSITY = 0.8
