export PLATFORM = asap7
export DESIGN_NAME = PEDynamic2
export DESIGN_NICKNAME = PEDynamic2
export VERILOG_FILES = $(sort $(wildcard ./designs/src/$(DESIGN_NICKNAME)/*.v))
export SDC_FILE = ./designs/$(PLATFORM)/$(DESIGN_NICKNAME)/constraint.sdc
export IO_CONSTRAINTS = ./designs/$(PLATFORM)/$(DESIGN_NICKNAME)/io.tcl
export DIE_AREA = 0 0 14 30
export CORE_AREA = 0 0 14 30
export PLACE_DENSITY = 0.9
export SYNTH_HIERARCHICAL = true
export HAS_IO_CONSTRAINTS = true
export ENABLE_DP0 = true
export GPL_ROUTABILITY_DRIVEN = true
export ABC_AREA = true
